# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 496)
        self.connect = QtWidgets.QPushButton(Form)
        self.connect.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.connect.setAutoFillBackground(False)
        self.connect.setStyleSheet("")
        self.connect.setObjectName("connect")
        self.disconnect = QtWidgets.QPushButton(Form)
        self.disconnect.setGeometry(QtCore.QRect(120, 40, 91, 41))
        self.disconnect.setObjectName("disconnect")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 90, 671, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.treeView = QtWidgets.QTreeView(self.tab)
        self.treeView.setGeometry(QtCore.QRect(10, 10, 631, 201))
        self.treeView.setObjectName("treeView")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(540, 160, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.logs = QtWidgets.QTextEdit(self.tab_2)
        self.logs.setGeometry(QtCore.QRect(10, 10, 651, 191))
        self.logs.setObjectName("logs")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.curreninfo = QtWidgets.QTextEdit(self.tab_3)
        self.curreninfo.setGeometry(QtCore.QRect(0, 0, 661, 201))
        self.curreninfo.setObjectName("curreninfo")
        self.getinfo = QtWidgets.QPushButton(self.tab_3)
        self.getinfo.setGeometry(QtCore.QRect(392, 150, 261, 41))
        self.getinfo.setObjectName("getinfo")
        self.tabWidget.addTab(self.tab_3, "")
        self.infobox = QtWidgets.QTextEdit(Form)
        self.infobox.setGeometry(QtCore.QRect(20, 349, 671, 131))
        self.infobox.setObjectName("infobox")
        self.update = QtWidgets.QPushButton(Form)
        self.update.setGeometry(QtCore.QRect(550, 430, 131, 41))
        self.update.setObjectName("update")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.connect.setText(_translate("Form", "Connect"))
        self.disconnect.setText(_translate("Form", "Disconnect"))
        self.pushButton.setText(_translate("Form", "Select File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Select update file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Logs"))
        self.getinfo.setText(_translate("Form", "Get previous version info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "current version"))
        self.update.setText(_translate("Form", "Update Controller"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
